### PR TITLE
feat: More semantic HTML & CSS theming

### PR DESCRIPTION
**Pull request by andi1984**
With this change, we include a couple of smaller changes on the HTML and
CSS side.

HTML:

- Moving the author as a subheadline for an improved visbility
- Using <details> element for listing further detailed information of
  the theme or the author.

CSS:

- Making use of CSS custom properties passing certain theme colors
  into the main CSS as a custom property and use them for styling the
  actual webview for each theme individually.
- For A11Y we need to make sure to choose the color combinations wisely,
  thus we choose the editor background and foreground color the
  theme author has chosen for the theme itself. This means if the author
  followed A11Y standards, we should meet those standards as well.

### CODE REVIEW

**Comment by andi1984** [comment]
Example:

Bildschirmfoto von 2021-04-22 00-55-27
Bildschirmfoto von 2021-04-22 00-56-35


@MichaelJolley Sorry, I think my pre-installed Prettier messed up aka. reformatted the files on save. I could try to do the changes in the files, but not using prettier for formatting. Have you used some specific formatting rules on your local machine?

**Comment by andi1984** [comment]
Narrow viewport:

Bildschirmfoto von 2021-04-22 00-55-23

**Comment by MichaelJolley** [comment]
I REALLY dig this @andi1984. One thing we need to account for: we don't have HSL on all themes so we can't depend on those properties to exist. In that case, we need to fail gracefully.

**Review by MichaelJolley — APPROVED** [review]

**Comment by MichaelJolley** [comment]
@all-contributors please add @andi1984 for code

**Pull request merged**
